### ISSUE TITLE
Could not generate/find CargoDb.s3db

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aivascu/ndddsample#4]
```
What steps will reproduce the problem?
1. build.bat--error
2. run_NDDDSample --error

What is the expected output? What do you see instead?
I see the dos prompt crashed, and i dont see CargoDb.s3db as defined in 
hibernate.cfg.xml

What version of the product are you using? On what operating system?
My OS is windows 7 ultimate 64bit



```

Original issue reported on code.google.com by `galib...@gmail.com` on 31 May 2012 at 8:58

**Comment by aivascu** [comment]
Not sure if the database was originally intended to be auto-generated but this can be worked around by manually creating a SQLite database file and providing the full path in the hibernate.cfg.xml.
